title: Pignatelli Lab
description: A GitHub Pages site containing Pignatelli Lab data analysis scripts.
theme: just-the-docs

url: https://pignatelli-lab.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
